import './globals.css'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import { ThemeProvider } from '@/provider/theme-provider'
import Navbar from '@/components/home/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'GetGud | ALL-IN-ONE Productivity App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <ThemeProvider>
            <Navbar />
            {children}
            <footer>
              <div className="flex items-center justify-center w-full h-16 border-t-2 border-gray-400/20">
                <span className="text-sm ">
                  Made with ❤️ by{" "}
                  <a
                    href="https://github.com/CantBeSubh"
                    className="font-bold text-blue-500"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    @CantBeSubh
                  </a>
                </span>
              </div>
            </footer>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}