import './globals.css'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import { ThemeProvider } from '@/provider/theme-provider'
import Navbar from '@/components/home/navbar'
import Footer from '@/components/home/footer'
import { OptionProvider } from '@/provider/option-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'GetGud | ALL-IN-ONE Productivity App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <div className='text-white bg-[#1f2029]'>
            <Navbar />
            <div className='h-screen'>
              <OptionProvider>
                {children}
              </OptionProvider>
            </div>
            <Footer />
          </div>

        </body>
      </html>
    </ClerkProvider>
  )
}